#!/usr/bin/env python3
"""
md_to_pdf.py — Converts ifu/<year>/README.md to ifu/<year>/report.pdf.

Usage:
    python src/md_to_pdf.py <year> [--ifu-root <dir>]

Converts the Markdown report generated by unified_readme.py to PDF via a
headless browser (Edge or Chrome). Requires Edge or Chrome to be installed.
"""
import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import markdown


_BROWSER_PATHS = [
    r'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe',
    r'C:\Program Files\Microsoft\Edge\Application\msedge.exe',
    r'C:\Program Files\Google\Chrome\Application\chrome.exe',
    r'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe',
]

_CSS = """
@page { margin: 2cm; }
body {
    font-family: Arial, sans-serif;
    font-size: 10pt;
    line-height: 1.5;
    color: #222;
}
h1 {
    font-size: 18pt;
    border-bottom: 2px solid #333;
    padding-bottom: 0.3em;
}
h2 {
    font-size: 14pt;
    border-bottom: 1px solid #ccc;
    padding-bottom: 0.2em;
    margin-top: 1.5em;
}
h3 { font-size: 11pt; }
table {
    border-collapse: collapse;
    width: 100%;
    margin: 0.8em 0;
    font-size: 9pt;
}
th, td { border: 1px solid #bbb; padding: 5px 8px; text-align: left; }
th { background-color: #e8e8e8; font-weight: bold; }
blockquote {
    border-left: 4px solid #aaa;
    margin: 0.5em 0;
    padding: 0.2em 0.8em;
    color: #555;
    background: #f9f9f9;
}
ul, ol { margin: 0.3em 0 0.3em 1.5em; }
li { margin: 0.2em 0; }
p { margin: 0.4em 0; }
"""


def _readme_path(ifu_root: Path, year: int) -> Path:
    return ifu_root / str(year) / 'README.md'


def _pdf_path(ifu_root: Path, year: int) -> Path:
    return ifu_root / str(year) / 'report.pdf'


def _preprocess(text: str) -> str:
    text = text.replace('✓', 'Oui')
    return text.replace('⚠', '(!)')


def _to_html(markdown_text: str) -> str:
    body = markdown.markdown(_preprocess(markdown_text), extensions=['tables'])
    return (
        f"<!DOCTYPE html><html><head>"
        f"<meta charset='utf-8'>"
        f"<style>{_CSS}</style>"
        f"</head><body>{body}</body></html>"
    )


def _find_browser() -> str:
    found = next((p for p in _BROWSER_PATHS if Path(p).exists()), None)
    if not found:
        raise RuntimeError("No supported browser (Edge or Chrome) found.")
    return found


def _print_to_pdf(html_path: Path, output_path: Path) -> None:
    subprocess.run(
        [_find_browser(), '--headless', '--disable-gpu',
         f'--print-to-pdf={output_path.resolve()}', str(html_path.resolve())],
        check=True, capture_output=True,
    )


def _write_pdf(html_content: str, output_path: Path) -> None:
    tmp_dir = Path(tempfile.mkdtemp())
    html_path = tmp_dir / 'report.html'
    html_path.write_text(html_content, encoding='utf-8')
    _print_to_pdf(html_path, output_path)
    shutil.rmtree(tmp_dir, ignore_errors=True)


def _read_readme(ifu_root: Path, year: int) -> str:
    readme = _readme_path(ifu_root, year)
    if not readme.exists():
        print(f"README not found: {readme}", file=sys.stderr)
        sys.exit(1)
    return readme.read_text(encoding='utf-8')


def _convert(ifu_root: Path, year: int) -> Path:
    markdown_text = _read_readme(ifu_root, year)
    html_content = _to_html(markdown_text)
    output_path = _pdf_path(ifu_root, year)
    _write_pdf(html_content, output_path)
    return output_path


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert ifu/<year>/README.md to report.pdf",
    )
    parser.add_argument('year', type=int, help='Fiscal year (e.g. 2024)')
    parser.add_argument(
        '--ifu-root', default='ifu-new',
        help="Root output directory (default: 'ifu-new')",
    )
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    output_path = _convert(Path(args.ifu_root), args.year)
    print(f"PDF -> {output_path}")


if __name__ == '__main__':
    main()
